name             'env_ws_phonebook'
maintainer       'Christoph Lukas'
maintainer_email 'christoph.lukas@gmx.net'
license          'All rights reserved'
description      'Installs/Configures phonebook test environment'
long_description 'Installs/Configures phonebook test environment'
version          '0.2.0'

depends 'pw_base', '=0.2.0'
depends 'ws_phonebook', '=0.2.0'
